name: Build And Deploy To ECS

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:                             
  build-and-deploy:
    runs-on: ubuntu-latest        
    steps:                        
    - uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18.18.0' 

    - name: Install pnpm
      run: npm install pnpm

    - name: Install dependencies
      run: pnpm install --force

    - name: Build static
      run: npm run build

    - name: Deploy to net0backend server        
      uses: easingthemes/ssh-deploy@v3.0.0      
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY }} 
        ARGS: "-avzr --delete"
        SOURCE: "dist/*"
        REMOTE_HOST: ${{ secrets.HOST }}
        REMOTE_USER: ${{ secrets.USER }}
        TARGET: "/var/www/nsfw/"
